# Creating token embeddings

Illustration of how the token ID to embedding vector conversion works with a hands on example.

Suppose we have the following four tokens with IDs 2, 3, 5 and 1.

In [1]:
import torch
input_ids=torch.tensor([2,3,5,1])

For the sake of simplicity we are going to use a small vocabulary of 6 words(instead of 50,257 words in the BPE tokenizer vocabulary), and we want to create embeddings of size 3(in GPT-3 the embedding size is 12,288 dimentions).


vocab: Each of these 6 words will be mapped in R3

quick-->4

fox-->0

is-->3

in-->2

the-->5

house-->1

torch.nn.Embedding return a simple lookup table that stores embeddings of a fixed dictionary and size.

In [7]:
vocab_size=6
output_dim=3

torch.manual_seed(123)
embedding_layer = torch.nn.Embedding(vocab_size, output_dim) #creates a dictionary
#this initialize the weights of the embedding matrix in a random manner

In [8]:
print(embedding_layer.weight)
#these are the initial weights which needs to be optimized during LLM training as part of the LLM optmization itself.

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.1690],
        [ 0.9178,  1.5810,  1.3010],
        [ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096]], requires_grad=True)


In [4]:
print(embedding_layer(torch.tensor([3])))

tensor([[-0.4015,  0.9666, -1.1481]], grad_fn=<EmbeddingBackward0>)


In [10]:
print(embedding_layer(input_ids))

# a look up operation that retrieves rows from the embedding layer weight matrix using a token ID.

tensor([[ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-2.8400, -0.7849, -1.4096],
        [ 0.9178,  1.5810,  1.3010]], grad_fn=<EmbeddingBackward0>)


Positional embeddings (Encoding word positions):

We encode the input tokens into 256-dimensional vector representation.

Assumption: The token IDs were created by the BPE tokenizer which has a vocabulary size of 50,257.

In [6]:
vocab_size=50257
optput_dim=256
token_embedding_layes=torch.nn.Embedding(vocab_size, output_dim)